## ndarray 多维数组对象

### 创建ndarray

In [3]:
import numpy as np

> array函数

In [4]:
#一维数组
a = [1,2,3,4]
arr = np.array(a)
arr.dtype #数据类型
np.shape(arr)

(4,)

In [59]:
#多维数组
a = [[1.0,2.3,4.5],[10.1,11.3,12.3]]
arr= np.array(a)
arr.shape #数组维度

(2, 3)

>arange函数

In [60]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

>特定类型的数组，接受数组作为参数，数据类型默认float64

In [61]:
#全1数组
np.zeros((2,3)) #2行3列
np.ones((3,4))
# np.ones_like(arr) #模仿特定数组的形状和数据类型新建
# np.zeros_like

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [62]:
np.eye(4)
np.identity(3) #n维单位矩阵
# np.empty()
# np.empty_like() #分配空间不填充值


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 数据类型

> 包括：(int unit 整型)  float  complex bool 
object string  unicode

>dtype 特殊对象，显示或指定数据类型

In [63]:
arr = np.array(a,dtype = np.int16)
arr

array([[ 1,  2,  4],
       [10, 11, 12]], dtype=int16)

>astype 显示的转换数据类型,在内存中拷贝旧数据

In [64]:
arr_float=arr.astype(np.float64)

### 矢量化

>数组与标量、相同维度的数组之间的运算，拓展到元素级

>不同维度之间的运算为广播：boardcasting

In [65]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr*arr1

array([[ 1,  4, 12],
       [40, 55, 72]])

In [66]:
# arr2 = np.array([[1,2],[3,4],[5,6]])
# arr1*arr2

### 基本索引与切片

>索引与切片获得原始数组的视图，任何修改都会反映到原数组上

>一维数组易于理解

In [67]:
#索引
arr[1][2]
arr[1,1]

11

In [68]:
#切片
arr3 = np.arange(10)
slice=arr3[3:5]
cs = slice.copy()  #显式复制
slice[:] = 1 #赋值
arr3

array([0, 1, 2, 1, 1, 5, 6, 7, 8, 9])

>多维数组，比如2\*2\*3的数组

>无论列表或数组，多维只是嵌套，通过索引取值不难，难在对于切片的理解

>多维数组引入轴的概念,比较难于理解

In [81]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d[0,1,2]

6

In [82]:
#reshape 设定数组的维度
arr3d = np.arange(27).reshape((3,3,3))
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [83]:
slice3 = arr3d[:2,:2,:2]
slice3

array([[[ 0,  1],
        [ 3,  4]],

       [[ 9, 10],
        [12, 13]]])

### 布尔型索引

>创建储存数据和姓名的索引

In [102]:
data = np.random.randn(6,4)  #返回正态分布的随机数据
data

array([[ 0.02091876,  1.66829898,  1.50112722,  0.04337349],
       [-0.1344197 ,  0.23278946,  2.5194745 , -1.5319854 ],
       [ 0.35626137, -0.19128075, -0.19814255,  0.08081567],
       [-0.43709668, -1.19450398,  0.8387023 , -0.55382618],
       [ 1.56872145,  0.22774721, -1.26694522, -0.01686059],
       [-0.88314659, -1.49236409,  0.79059994, -0.25648702]])

In [103]:
name = np.array(['A','B','C','A','B','D']) #unicode 1个字符
name

array(['A', 'B', 'C', 'A', 'B', 'D'], dtype='<U1')

>通过比较运算符获得布尔型的数组，与data数组的轴长度一致

In [104]:
name == 'A'

array([ True, False, False,  True, False, False])

In [105]:
data[name == 'A']

array([[ 0.02091876,  1.66829898,  1.50112722,  0.04337349],
       [-0.43709668, -1.19450398,  0.8387023 , -0.55382618]])

> 与切片，整数相结合，注意取值的轴

>数据创建副本

In [106]:
data[name == 'A',2]

array([1.50112722, 0.8387023 ])

>利用布尔型索引，轻松赋值

>&和 |或 ！=  ~ 否 布尔运算依然适用

In [107]:
data[~((name == 'A')|(name == 'B'))]

array([[ 0.35626137, -0.19128075, -0.19814255,  0.08081567],
       [-0.88314659, -1.49236409,  0.79059994, -0.25648702]])

In [108]:
data[data<0]=0  # 批量赋值
data

array([[0.02091876, 1.66829898, 1.50112722, 0.04337349],
       [0.        , 0.23278946, 2.5194745 , 0.        ],
       [0.35626137, 0.        , 0.        , 0.08081567],
       [0.        , 0.        , 0.8387023 , 0.        ],
       [1.56872145, 0.22774721, 0.        , 0.        ],
       [0.        , 0.        , 0.79059994, 0.        ]])

### 花式索引（fancy indexing）

>利用整数数组进行索引

In [111]:
arr = np.empty((8,3))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.],
       [5., 5., 5.],
       [6., 6., 6.],
       [7., 7., 7.]])

In [112]:
#整数列表、ndarray用于指定顺序
arr[[0,3,5]]

array([[0., 0., 0.],
       [3., 3., 3.],
       [5., 5., 5.]])

In [113]:
#倒叙查找
arr[[-1,-4,-3]]

array([[7., 7., 7.],
       [4., 4., 4.],
       [5., 5., 5.]])

In [115]:
#当传入多个数组时，组成类似坐标，得到一维数组
arr[[3,5],[0,2]]

array([3., 5.])

>矩形区域选取的方法

In [117]:
arr[[3,5]][:,[0,2]]

array([[3., 3.],
       [5., 5.]])

In [119]:
# 将2个一维整数数组转换为方形区域索引器
arr[np.ix_([3,5],[0,2])]

array([[3., 3.],
       [5., 5.]])

### 数组转置 transpose

> 返回数据的视图

In [121]:
#二维数组
arr2d = np.arange(15).reshape((3,5))
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [122]:
arr2d.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [124]:
arr2d.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [125]:
#计算矩阵的内积
np.dot(arr2d.T,arr2d)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [126]:
np.dot(arr2d,arr2d.T)

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])