## 通用函数：元素级数组函数 

>简单函数的矢量化包装

### 一元 ufunc

In [72]:
import numpy as np
arr = np.arange(1,11)
x = np.random.randn(7)
y  = np.random.randn(7)
print(arr,x,y)

[ 1  2  3  4  5  6  7  8  9 10] [-1.37544153 -0.20810066  0.61988489 -0.86691909 -0.06040985  0.1406421
  0.23186512] [ 1.59319049 -1.18322396 -2.09500911 -1.07261903  0.77162433  0.46746781
 -1.12717073]


In [73]:
#整数、浮点数、负数绝对值
abs(x)
np.fabs(y)

array([1.59319049, 1.18322396, 2.09500911, 1.07261903, 0.77162433,
       0.46746781, 1.12717073])

In [74]:
#平方根
np.sqrt(arr)
#平方
np.square(arr)
#指数ex
np.exp(arr)
#对数 log10  log2 
np.log10(arr)
np.log1p(arr) #x + 1

array([0.69314718, 1.09861229, 1.38629436, 1.60943791, 1.79175947,
       1.94591015, 2.07944154, 2.19722458, 2.30258509, 2.39789527])

In [75]:
#对应元素的正负，返回1，0，-1
np.sign(x)
np.ceil(x)  #大于元素的最小整数
np.floor(x) #小于元素的最小整数
np.rint(x) #四舍五入，保留dtype
np.modf(x) #返回整数和小数部分，独立的数组
np.isnan(x) # 判断是否为数字，不是数字返回True
np.isinf(x) #判断哪些是无穷的
#np.isfinite(x) #判断哪些是有穷的

array([False, False, False, False, False, False, False])

In [76]:
#三角函数和反三角函数
#cos sin tan
#双曲型三角函数  定义域从实数扩展到虚数
np.cos(arr)
np.cosh(arr)
#np.arccos(x)

array([1.54308063e+00, 3.76219569e+00, 1.00676620e+01, 2.73082328e+01,
       7.42099485e+01, 2.01715636e+02, 5.48317035e+02, 1.49047916e+03,
       4.05154203e+03, 1.10132329e+04])

In [77]:
#0为真，其余为假
np.logical_not(-1)
np.logical_not(0)
np.logical_not(1)

False

### 二元ufunc

In [78]:
#加减乘除
np.add(x,y)
np.multiply(x,y)
np.subtract(x,y)
np.divide(x,y)
np.floor_divide(x,y) #除法的整除
# # np.power(x,y)  #A的B次mi
np.mod(x,y) #求模 除法的余数

array([ 0.21774897, -0.20810066, -1.47512423, -0.86691909,  0.71121448,
        0.1406421 , -0.89530561])

In [79]:
#比较
np.maximum(x,y) #元素最大值
np.minimum(x,y) #元素最小值
np.fmax(x,y)
np.fmin(x,y) # 或略数组中的NaN
#np.greater np.greater_equal  np.less  np.less_equal np.equal np.not_equal
#对应比较运算符 > >= < <= == !=
np.copysign(x,y) #将y的符号传给x

array([ 1.37544153, -0.20810066, -0.61988489, -0.86691909,  0.06040985,
        0.1406421 , -0.23186512])

In [80]:
#逻辑运算
#x =np.array([1,0,1,1,1,0,0,1])
#y = np.array([1,0,0,1,1,1,0,0])
np.logical_and(x,y) #&
np.logical_or(x,y)  #|
np.logical_xor(x,y) #^异或

array([False, False, False, False, False, False, False])